### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by livrasand** [TitoMoi/servihelper#1]
Hello friend, I am Livrädo Sandoval, Jehovah's Witness from Mexico. Author of Attendant Zoom (an application to share multimedia in meetings) and JWPUB Catalog (a catalog of own JWPUB files). I am developing an application for elders and ministerial servants in Svelte and Electron. I would love it if you could support my project. I have looked at this project and I liked it. What are you saying? Will you join us? We are currently 3 siblings (Mexico, Spain and Brazil). You can visit my website: goattendant.com and meet Kingdom Hall Attendant.

**Comment by TitoMoi** [comment]
Hello Livrädo! Thanks for getting in touch, currently i have no spare time...but let me know by email if you face some problem with Electron, maybe i can help ^^
